# 异常处理

## 异常概述

### 什么是程序的异常

在使用计算机语言进行项目开发的过程中，即便程序员把代码写得尽善尽美，在系统的运行过程中仍然会遇到一些问题，因为很多问题不是靠代码能够避免的，比如：`客户输入数据的格式问题`，`读取文件是否存在`，`网络是否始终保持通畅`等等。

* **异常**：指的是程序在执行过程中，出现的非正常情况，如果不处理最终会导致JVM的非正常停止。

> 异常指的并不是语法错误和逻辑错误。
>
> 语法错了，编译不通过，不会产生字节码文件，根本不能运行。
>
> 代码逻辑错误，只是没有得到想要的结果，例如：求a与b的和，写成了a-b。

### 异常的抛出机制

Java中把不同的异常用不同的类表示，一旦发生某种异常，就创建`该异常类型的对象`，并且`抛出`（throw）。然后程序员就可以`捕获`（catch）到这个异常对象，并处理；如果没有捕获（catch）这个异常对象，那么这个异常对象将会导致`程序终止`。

举例：

运行下面的程序，程序会产生一个数组角标越界异常`ArrayIndexOfBoundsException`。

我们通过图解来解析下异常产生和抛出的过程。

```java
public class ArrayTools {
    // 对给定的数组通过给定的角标获取元素。
    public static int getElement(int[] arr, int index) {
        int element = arr[index];
        return element;
    }
}
```

测试类

```java
public class ExceptionDemo {
    public static void main(String[] args) {
        int[] arr = { 34, 12, 67 };
        intnum = ArrayTools.getElement(arr, 4)
        System.out.println("num=" + num);
        System.out.println("over");
    }
}
```

上述程序执行过程图解：

![](.\images\异常产生过程.png)

### 如何对待异常

对于程序出现的异常，一般有两种解决方法：一是遇到错误就终止程序的运行。另一种方法是程序员在编写程序时，就充分考虑到各种可能发生的异常和错误，极力预防和避免。实在无法避免的，要编写相应的代码进行异常的检测、以及`异常的处理`，保证代码的`健壮性`。

## Java异常体系

### Throwable

`java.lang.Thorwable` 类是Java程序执行过程中发生的异常时间对应的类的根父类。

**Throwable中常用的方法**：

* `public void printStackTrace()`：打印异常的详细信息。

  包含了异常的类型、异常的原因、异常出现的位置、在开发和调试阶段都得使用printStackTrace。

* `public String getMessage()`：获取发生异常的原因。

### Error和Exception

Throwable可分为两类：Error和Exception。分别对应着`java.lang.Error`与`java.lang.Exception`两个类。

#### Error

**Error**：Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。一般不编写针对性的代码进行处理。

* 例如：`StackOverflowError`（栈内存溢出）和`OutOfMemoryError`（堆内存溢出，简称OOM）。

Error举例1：栈内存溢出异常

比如：无限递归调用方法，这时就会造成栈内存溢出异常，在栈里面创建了很多的栈帧，并且无法得到销毁。

```java
@Test
public void test2(){
    test2();
}
```

这个时候，就会无限地去递归调用test2()方法，不停地在栈中创建栈帧，最终导致栈内存溢出StackOverflowError。

![image-20231203133246930](.\images\image-20231203133246930.png)





Error举例2：堆内存溢出异常

比如：无限循环创建对象，这时就会造成堆内存溢出异常，在堆内存中创建了多个对象且无法得到销毁。

```java
@Test
public void test(){
    ArrayList<Person> arrayList = new ArrayList();
    while (true){
        Person p1 = new Student();
        arrayList.add(p1);
    }
}
```

这个时候，就会不停地在堆空间中创建Student对象，堆空间内存不断地减少，从而造成堆内存溢出异常。



#### Exception

**Exception**：其他因编程错误或偶然的外在因素导致的一般性问题，需要使用针对性的代码进行处理，使程序继续运行。否则一旦发生异常，程序也会挂掉。例如：

* 空指针异常
* 试图读取不存在的文件
* 网络连接中断
* 数组角标越界

> 说明：
>
> 1. 无论是Error还是Exceptio，还有很多子类，异常的类型非常丰富。当代码运行出现异常时，特别是我们不熟悉的异常时，不要紧张，把异常的简单类名，拷贝到API中去了解它即可。
> 2. 我们本章讲的异常处理，其实针对的就是Exception。

<img src="C:\Users\14036\Desktop\markdown笔记\JavaSE\images\image-20220511161910951.png" alt="image-20220511161910951" style="zoom:67%;" />





### 编译时异常和运行时异常

Java程序的执行分为编译时过程和运行时过程。有的错误只有在`运行时`才会发生。比如：除数为0，数组下标越界第。

<img src="C:\Users\14036\Desktop\markdown笔记\JavaSE\images\image-20220330002449526.png" alt="image-20220330002449526" style="zoom:80%;" />

因此，根据异常可能出现的阶段，可以将异常分为：

* **编译时异常**（即checked异常、受检异常）：在代码编译阶段，编译器就能明确`警示`当前代码`可能发生（不是一定发生）`xx异常，并`明确督促`程序员提前编写处理它的代码。如果程序员`没有编写`对应的异常处理代码，则编译器就会直接判定编译失败（在编译期间就无法通过），从而不能生成字节码文件。通常，这类异常的发生不是由程序员的代码引起的，或者不是靠简单的判断就可以避免的。例如：FileNotFoundException（文件找不到异常）。
* **运行时异常**（即runtime异常、unchecked异常、非受检异常）：在代码编译阶段，编译器完全不做任何检查，无论该异常是否会发生，编译器都不给出任何提示。只有等代码运行起来并确实发生了xx异常，它才能被发现。通常，这类异常是由程序员的代码编写不当引起的，只要稍加判断，或者细心检查就可以避免。
  * **`java.lang.RuntimeException`**类及它的子类都是运行时异常。比如：ArrayIndexOutOrBoundsException数组下标越界异常，ClassCastException类型转换异常。

> **编译时异常一定要处理，否则运行不通过；**
>
> **运行时异常可在出现异常后再改BUG。**

<img src=".\images\1562771528807.png">





编译时异常与运行时异常的区别就在于，一个是在编译时就会报错，需要程序员发生编译时异常的代码进行处理，使用向上抛（throws）或者try...catch的方式进行处理；一个是运行时异常，只有在运行后才知道会不会报错，不需要程序员在编译代码时就进行处理。在底层代码中，实际上编译时异常也是通过手动throw出来的，然后通过向上抛的方式，让程序员明白当前的代码会出现编译时异常，然后自己进行处理。例如，下面是FileNotFoundException文件找不到异常（编译时异常）：



![image-20231203143935410](.\images\image-20231203143935410.png)



## 异常的处理

### 异常处理的概述

在编写程序时，经常要在可能出现错误的地方加上检测的代码，如进行x/y运算时，要`检测分母为0`，`数据为空`，`输入的不是数据而是字符`等。过多的if-else分支会导致程序的`代码加长`、`臃肿`、`可读性差`，程序员需要花很大的精力“`堵漏洞`”。因此采用异常处理机制。

**Java异常处理**

Java采用的是异常处理机制，是`将异常处理的程序代码集中在一起`，与正常的程序代码分开，使得程序简洁、优雅、并易于维护。



**Java异常处理的方法**：

> * **方式一：`try-catch-finally`**
> * **方式二：`throws + 异常类型`**



### 方式一：捕获异常（try-catch-finally)

#### 1、**Java异常处理的`抓抛模型`**

* Java程序的执行过程中出现异常，会生成一个对应的异常类对象，该异常对象将被提交给Java运行时系统，这个过程称为`抛出（throw）异常`。
* 如果一个方法内抛出异常，该异常对象会被抛给调用者方法中处理。如果异常没有在调用者方法中处理，它继续被抛给这个调用方法的上层方法。这个过程将一直继续下去，直到异常被处理。这一过程称为`捕获（catch）异常`。
* 如果一个异常回到main()方法，并且main()也不处理，则程序运行终止。



#### 2、**try-catch-finally基本格式**

**捕获异常语法如下：**

```java
try{
    .....	//可能产生异常的代码
}catch( 异常类型1 e ){
    .....	//当产生异常类型1时的处置措施
}catch( 异常类型2 e ){
    .....	//当产生异常类型2时的处置措施
}finally{
    .....	//无论是否发生异常，都会无条件执行的雨具
}
```

#### 3、try...catch使用及案例

##### 1）try

捕获异常的第一步是用`try{...}语句`块选定捕获异常的范围，将可能出现异常的业务逻辑代码放在try语句块中。

##### 2）catch

catch分支，分为两个部分，catch()中编写异常类型和异常类型对象参数名，大括号{}中编写的是如果发生了()中声明的异常，要做什么样处理的代码。

##### **3）整体执行过程：**

当某段代码可能发生异常，不管这个异常是编译时异常（受检异常）还是运行时异常（非受检异常），我们都可以使用try块将它括起来，并在try块下面编写catch分支尝试捕获对应的异常对象。

如果是编译时异常，在编译期间就会报错， 这个时候我们就可以使用try块将这部分代码括起来，然后使用catch捕获编译的异常。

如果是运行时异常，对于可能会发生的异常部分，我们也可以使用try-catch语句，将这部分括起来。

**执行过程：**

> * 如果在程序运行时，**try块中的代码没有发生异常，那么catch所有的分支都不执行**。
> * 如果在程序运行时，try块中的代码发生了异常，根据异常对象的类型，**将从上到下选择`第一个匹配`的catch分支执行。此时try中发生异常语句下面的代码将不执行，而整个try...catch之后的代码可以继续运行。**
> * 如果在程序运行时，try块中的代码发生了异常，但是**当所有catch分支都无法匹配（捕获）这个异常，那么JVM将会终止当前方法的执行，并把异常对象“抛”给调用者**。如果调用者不处理，程序就挂了。



<img src=".\images\image-20220503122722605.png" alt="image-20220503122722605" style="zoom:67%;" />



##### 4）使用注意点：

> 1. **如果明确知道产生的产生的何种异常，可以用该异常类作为catch的参数；也可以用其父类作为catch的参数。**出现异常时实际上是创建了一个异常类的对象，由于创建对象时会去创建其父类的对象，所以catch也能够捕获其父类的对象。
>
>    比如：可以用ArithmeticException类作为参数的地方，就可以用RuntimeException类作为参数，或者用所有异常的父类Exception类作为参数。但不能是与ArithmeticException类无关的异常，如NullPointerException（catch中的语句将不会执行）。
>
> 2. **每个try语句块都可以伴随一个或多个catch语句，用于处理可能产生的不同类型对象。**
>
> 3. **如果有多个catch分支，并且多个异常类型有父子类关系，必须保证小的子异常类型在上，大的父异常类型在下。否则，报错。**
>
>    这里和if...else...不同，if...else...中如果后续不会被执行到，也不会报错；但是try...catch语句中，如果后续的catch语句不可能被执行到，则报错。
>
>    比如：报ArithmeticException异常，如果将其父类RuntimeException放在上面，那么只要匹配到RuntimeException就不会再对后续的catch语句进行匹配。所以，需要将范围较小的异常类型放在上面，范围大的异常类型放在下面。
>
> 4. **cacth中常用的异常处理方式：**
>
>    * `public String getMessage()`：获取异常的描述信息，返回字符串
>    * `public void printStackTrace()`：打印异常的跟踪栈信息并输出到控制台。包含了异常的类型、异常的原因、还包含异常出现的位置，在开发和调试阶段，都得使用printStackTrace()。

<img src=".\images\image-20220331180736381.png" alt="image-20220331180736381" style="zoom:80%;" />

##### 5）使用案例：

案例1：

```java
@Test
public void test3() {
    try {
        System.out.println("开始执行异常信息");
        int i = 1 / 0;
        System.out.println("结束执行异常信息");
    }catch (ArithmeticException ae){
        //打印异常信息
        ae.printStackTrace();
    }
}
```

执行结果：

![image-20231203171332743](.\images\image-20231203171332743.png)

从上例可以了解到的是，在try语句中，一旦执行到异常语句后，后续的代码就不会再执行了。printStackTrace()方法用于打印异常的信息。



案例2：

```java
@Test
public void test4(){
    try {
        int[] ints = new int[]{1, 2, 3, 4};
        for (int i = 0; i < 5; i++) {
            System.out.println(ints[i]);
        }
    } catch (RuntimeException e){
        e.printStackTrace();
    }catch (ArrayIndexOutOfBoundsException e){//报错
        e.printStackTrace();
    }
}
```

这里会报错，原因在于RuntimeException是ArrayIndexOutOfBoundsException的父类，就算try语句中会出现ArrayIndexOutOfBoundsException异常，也永远到不了第二个catch语句中，因为RuntimeException会进行捕获，所以出现了编译时错误。

所以在编写代码时：

> **catch语句中从上到下应当是范围从小到大。**

当对代码进行修改后：

```java
@Test
public void test4() {
    try {
        int[] ints = new int[]{1, 2, 3, 4};
        for (int i = 0; i < 5; i++) {
            System.out.println(ints[i]);
        }
    } catch (ArrayIndexOutOfBoundsException e) {
        e.printStackTrace();
    } catch (RuntimeException e) {
        e.printStackTrace();
    }
}
```

执行结果：

![image-20231203172619889](.\images\image-20231203172619889.png)

可以看到，当执行了一个catch语句后，后续的catch语句将不会再执行。

#### 4、finally使用及案例

**finally使用场景：**

因为异常会引发程序跳转，从而导致有些语句执行不到。而程序中有一些特定的代码无论异常是否发生，都需要执行。例如，数据库连接、输入流输出流、Socket连接、Lock锁的关闭等，这些代码通常就会放到finally快中。所以，我们通常将一定要执行的代码声明在finally中。



<img src=".\images\image-20220331215517077.png" alt="image-20220331215517077" style="zoom: 80%;" />



> * 无论catch中的语句会不会执行，会不会报异常，有没有return语句，try语句中是否有异常事件，**`finally块中的语句都会被执行`**。
>
> * finally语句和catch语句是可选的，但finally不能单独使用。
>
>   ```java
>   try{
>                      
>   }finally{
>                     
>   } 
>   ```



**案例**：finally用来确保资源的关闭

```java
public class TestFinally {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        try {
            System.out.print("请输入第一个整数：");
            int a = input.nextInt();
            System.out.print("请输入第二个整数：");
            int b = input.nextInt();
            int result = a/b;
            System.out.println(a + "/" + b +"=" + result);
        } catch (InputMismatchException e) {
            System.out.println("数字格式不正确，请输入两个整数");
        }catch (ArithmeticException e){
            System.out.println("第二个整数不能为0");
        } finally {
            System.out.println("程序结束，释放资源");
            input.close();
        }
    }
    
    @Test
    public void test1(){
        FileInputStream fis = null;
        try{
            File file = new File("hello1.txt");
            fis = new FileInputStream(file);//FileNotFoundException
            int b = fis.read();//IOException
            while(b != -1){
                System.out.print((char)b);
                b = fis.read();//IOException
            }

        }catch(IOException e){
            e.printStackTrace();
        }finally{
            try {
                if(fis != null)
                    fis.close();//IOException
            } catch (IOException e) {
                e.printStackTrace();
            }	
        }
    }
}
```





假设catch语句中有return，finally语句中也有return，那这个时候到底是返回catch语句中的return，还是finally中的呢？

实际上应该是返回finally中的return值。原因就在于finally一定会被执行，后续的return语句占据了之前的return的返回值。

案例：

![image-20231203182847681](.\images\image-20231203182847681.png)

这里返回的就应该是0了。



#### 5、执行过程总结：

* **发生异常情况：**

  **`try语句` → `发生异常` → `停止并不再执行try语句` → `从上到下对异常类型进行匹配` → `一旦匹配成功，将执行catch语句` → `执行finally语句` → `执行try-catch-finally语句下面的代码`**

  若catch语句未捕获异常，则停止当前方法的执行，并将异常抛给调用者。

  

* **未发生异常情况：**

  **`执行try语句` → `执行finally语句` → `执行try-catch-finally语句下面的代码`**

一定注意的是，无论是否发生异常，catch语句只要成功捕获了异常，try-catch语句后续的代码依然会执行。



#### 6、异常处理的体会

* 前面使用的异常都是**`RuntimeException类`**或是它的**`子类`**，这些类的异常的特点是：即便没有使用try和catch捕获，Java自己也能捕获，并且编译通过（但运行时会发生异常使得程序运行终止）。所以，对于这类异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。
* 如果抛出的异常是IOException等类型的**`非运行时异常`**，则必须捕获，否则**`编译错误`**。也就是说，我们必须处理编译时异常，将异常进行捕捉，转化为运行时异常。



#### 7、自己对try-catch-finally语句的理解

try-catch-finally语句，实际上它的作用是让代码发生异常时，进行去执行代码，而不是直接报个异常，然后程序停止，然后rollback回滚。

它的作用是让程序就算出现了异常，后续的代码进行去执行，报异常就报一些异常信息出来，而不是停止程序的运行。

### 处理方式二：throws

* 如果在编写方法体的代码时，某句代码可能发生某个`编译时异常`，不处理编译不通过，但是在当前方法体中可能`不适合处理`或`无法给出合理的处理方式`，则此方法应`显示地`声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。

<img src=".\images\image-20220331112000671.png" alt="image-20220331112000671" style="zoom:67%;" />

* 具体方式：在方法声明中用`throws语句`可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。

#### 1、throws基本格式
**声明异常格式**：
```java
修饰符 返回值类型 方法名(参数) throws 异常类名1, 异常类名2...{
    //方法体
}
```

若有多个异常类型，使用逗号隔开。



举例：

```java
public void readFile(String file) throws FileNotFoundException, IOException {
	...
	//读文件操作可能产生FileNotFoundException和IOException类型的异常
	FileInputStream fis = new FileInputStream(file);
	...
}
```



#### 2、throws使用举例

举例：针对编译时异常

```java
public class TestThrowsCheckedException {
    public static void main(String[] args){
        System.out.println("上课......");
        //换到这里处理异常
        try {
            afterClass();
        } catch(InterruptedException e) {
            e.printStackTrace();
            System.out.println("准备提前上课");
        }
        System.out.println("上课.....");
    }
    
    //将异常向上抛
    public static void afterClass() throws InterruptedException {
        for(int i = 10; i>=1; i--){
            Threap.sleep(1000);
            System.out.println("距离上课还有：" + i + "分钟");
        }
    }
}
```



#### 3、方法重写中throws的要求

方法重写时，对于方法签名是有严格要求的。

现在我们先复习一下之前学习的方法重写的要求：

```
1. 方法名必须相同。
2. 形参列表必须相同。
3. 返回值类型：
    基本数据类型和void，必须相同
    引用数据类型：子类重写方法的返回值类型小于或等于父类的
4. 权限修饰符：重写的方法大于等于父类方法权限修饰符，而且要求父类被重写方法在子类中是可见的
5. 不能是static、final修饰的方法。
```

此外，对于throws异常列表要求：

> * **编译时异常**：
>
>   * 如果父类被重写的方法后面没有”`throws 编译时异常`“，那么重写后的方法也不能出现“`throws 编译时异常`“。
>   * 如果父类被重写的方法后有“`throws 编译时异常`”，那么子类重写的方法throws 编译时异常类型要求 **`<=`** 父类中被重写的方法throws编译时异常类型。或者子类重写的方法不throws编译时异常。
>
>   就是类似于方法的引用类型返回值，子类要求比父类中的小。
>
> * **运行时异常**：对于`throws运行时异常类型`没有要求

案例：

```java
public class Person {
    public void method() throws IOException {
        File file = new File("hello.txt");
        FileInputStream inputStream =  new FileInputStream(file);
        inputStream.read();
        inputStream.close();
    }
}
```

对于上例中，method()方法抛出了IOException，则对于其实现方法来说，其可以抛出IOException或其子类，或者不抛出。



所以很多接口或者抽象类中，定义的抽象方法中会去抛出编译时异常。

原因就在于其子类/实现类中重写的方法中有可能会去抛出编译时异常，而父类方法中抛出编译时异常类型必须大于等于子类中抛出的编译时异常类型，为了让重写的方法能够抛出异常，父类/接口中声明的抽象方法中必须声明比重写方法可能抛出编译时异常类型大的异常。





### 两种异常处理方法的选择

前提：对于异常，使用相应的处理方式。此时的异常，主要指的是编译时异常。

* 如果程序代码中，涉及到资源的调用（流、数据库连接、网络连接等），则必须考虑使用try-catch-finally来处理，保证不出现内存泄露。
* 如果父类被重写的方法没有throws异常类型，则子类重写的方法中如果出现异常，只能考虑使用try-catch-finally进行处理，不能throws。
* 开发中，方法a中依次调用了方法b,c,d等方法，方法b,c,d之间是递进关系。此时，如果方法b,c,d中有异常，我们通常选择使用throws，而方法a中通常选择使用try-catch-finally。



## 手动抛出异常对象：throw

Java中异常对象的生成有两种方式：

* 由虚拟机**自动生成**：程序运行过程中，虚拟机检测到程序发生了问题，那么针对当前问题，就会在后台自动创建一个对应异常类的实例对象并抛出。
* 由开发人员**手动创建**：`new 异常类型([实参列表]);`，如果创建好的异常对象不抛出对程序没有任何影响，和创建一个普通对象一样，一旦throw抛出了，就会对程序运行产生影响了。



### 为什么需要手动抛出异常对象

在实际开发中，如果出现不满足具体场景的代码问题，我们就有必要手动抛出一个指定类型的异常对象。

### 格式

```java
throw new 异常类名(参数);
```

手动地创建throw语句去抛出的异常对象，和JVM自动创建抛出的异常对象一样。底层都是通过使用throw去抛出。

> * **如果是`编译时异常`类型的对象，同样需要使用`throws`或try-catch处理，否则编译不通过。**
> * **如果是`运行时异常`类型的对象，`编译器不提示`。**
> * 可以抛出的异常必须是Throwable或其子类的实例。





### 使用注意点：

1. 无论是编译时异常类型的对象，还是运行时异常类型的对象，如果没有被try-catch合理的处理，都会导致程序崩溃。

2. throw语句会导致程序执行流程被改变，throw语句是明确抛出一个异常的对象，因此它`下面的代码将不会执行`。

3. 如果当前方法没有try-catch处理这个异常对象，throw语句就会`代替return语句`提前终止当前方法的执行，并返回一个异常对象给调用者。

使用案例：

```java
public class TestThrow {
    public static void main(String[] args) {
        try {
            System.out.println(max(4,2,31,1));
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            System.out.println(max(4));
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            System.out.println(max());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static int max(int... nums){
        if(nums == null || nums.length==0){
            throw new IllegalArgumentException("没有传入任何整数，无法获取最大值");
        }
        int max = nums[0];
        for (int i = 1; i < nums.length; i++) {
            if(nums[i] > max){
                max = nums[i];
            }
        }
        return max;
    }
}
```

实际上，对于编译时异常，在底层就是通过throw的方式去创建的编译时异常对象并throws向上抛，抛给调用者，使得我们在调用某一方法时，编译时就会报错，需要使用try-catch或者throws处理。

例如，在创建输入输出流时报的编译时异常：FileNotFoundException，实际上在底层中也是通过throw的方式创建，然后由于是编译时异常，必须进行处理，代码中将其向上抛给了调用者：

![image-20231204225409454](.\images\image-20231204225409454.png)





## 自定义异常

### 为什么需要自定义异常类

Java中不同的异常类，分别表示着某一种具体的异常情况。那么在开发中总是有些异常情况是核心类库中没有定义好的，此时我们需要根据自己业务的异常情况来定义异常类。例如年龄负数问题，考试成绩负数问题，某员工已在团队中等。

### 何时需要自定义异常类

如果有很多的异常，都属于一个类别的，比如输入的信息有误这一类别，那么我们就可以这些异常使用这一个类别的异常类去抛出，比如定义一个InputException。

如果是单个单个的异常的话，不属于某一个类别，仅仅是这一个模块中可能出现的异常，那么我们只需要使用现用的异常类比如RuntimeException，去抛出即可。

### 如何自定义异常类

（1）要继承一个异常类型

* 自定义一个编译时异常类型：继承于**`java.lang.Exception`**。
* 自定义一个运行时异常类型：继承于**`java.lang.RuntimeException`**。

（2）建议大家提供至少两个构造器，一个是无参构造，一个是(String message构造器，其中(String message)用于设置报错的提示信息，在构造器中调用父类构造器super(message)。

（3）自定义异常需要提供`serialVersionUID`。



案例，创建一个自定义的运行时异常，假设该异常用于输入的数字类型错误的情况：

```java
public class MyException extends RuntimeException{
    
    //提供serivalVersionUID
    @java.io.Serial
    static final long serialVersionUID = 1234567890L;
    
    public MyException(){
    }
    
    //带参的构造器
    public MyException(String message){
        super(message);
    }
}
```

测试用例：

```java
public class MyExceptionTest{
    //要求客户输入一段正整数，并返回数字的最大值，当输入的数字为0时，停止输入
    public int test(){
        int max = 0;
        Scanner scanner = new Scanner(System.in);
        System.out.println("请输入一串正整数：");
        //这里使用到了try-catch-finally，原因在于方法中有scanner资源需要进行关闭
        try {
            while (true) {
                String s = scanner.nextLine();
                //判断s是否是一串正整数数字类型
                if (s.matches("[0-9]+")) {
                    int i = Integer.parseInt(s);
                    if (i != 0) {
                        max = Math.max(i, max);
                    } else {
                        break;
                    }
                } else {
                    throw new MyException("输入的数字类型有误！");
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            scanner.close();
        }
        return max;
    }
}
```



### 注意点

1. 自定义的异常只能通过throw抛出。
2. 自定义异常最重要的是异常类的`名字`和`messaage`属性。当异常出现时，可以**根据名字判断异常类型**，**根据message具体判断异常信息**。比如：TeamException("成员已满，无法添加")、TeamException("该员工已是某团队成员了")；
3. 自定义异常对象只能手动抛出。抛出后由try-catch处理，也可以甩给throws给调用者处理。同时，对于运行时异常，也可不处理，直接报异常给前端。





## 小结

**异常处理的5个关键字：**

<img src=".\images\image-20220330003738109.png" alt="image-20220330003738109" style="zoom: 67%;" />
